![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.11. Veb sahifalardan oʻqish. JSON va API
**Bu vazifalarni bajargach, veb sahifalardan maʼlumot olish, JSON bilan ishlash va API soʻrovlarini yuborish koʻnikmalarini egallaysiz.**

#1-topshiriq
1. Pandas kutubxonasidan foydalanib, quyida berilgan link ichidan barcha jadvallarni o‘qing va roʻyxat shaklida saqlang.

Link 403 Forbidden (Manzil to'g'ri, lekin kirish taqiqlangan.) xatoligini bermasligi uchun, sahifani avval requests bilan yuklab, keyin pd.read_html() ga HTML matnini bering.

 * https://en.wikipedia.org/wiki/Fossil_fuel_exporters
2. Har bir jadvalning birinchi 1 qatorini ekranga chiqaring.

In [ ]:
import requests
import pandas  as pd
import io
url = "https://en.wikipedia.org/wiki/Fossil_fuel_exporters"

r = requests.get(url, headers = {"User-Agent": "Mozilla/5.0"})

if r.status_code == 200:
  html_flow = io.StringIO(r.text)
  data = pd.read_html(html_flow)
  for i in range(0,len(data)) :
    display(data[i].head(1))
    print("\n")
else:
  print("error!")

    0                                                  1
0 NaN  This article needs to be updated. Please help ...

   Rank Country/region                       Oil - exports Date of information
0     1   Saudi Arabia  6,658,642 bbl/d (1,058,639.5 m3/d)           2020 est.

   Rank Country/region  Natural gas - exports (cu m) Date of information
0     1         Russia                  199928345000           2020 est.

   Rank    Country  Coal - exports (thousand short tons)  Date of information
0     1  Indonesia                                451520                 2020

,vteLists of countries by energy rankings,vteLists of countries by energy rankings.1
0,Fossil Fuel,Petroleum All Production Consumption Exports I...

           0                                                  1
0  Petroleum  All Production Consumption Exports Imports Res...

         0                                   1
0  Uranium  All Production Generation Reserves

#2-topshiriq
Yuqorida yaratilgan jadvallar roʻyxatidan eng uzunini `largest_data.csv` fayliga saqlang.

In [ ]:
largest_df = data[0]
for i in range(0,len(data)):
  if len(data[i]) > len(largest_df):
    largest_df = data[i]

largest_df.to_csv('largest_data.csv')

#3-topshiriq
1. Quyidagi link orqali json maʼlumotni yuklab oling va uni climate_change_co2.json nomi bilan saqlang.
 * https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json
2. Maʼlumotlar boshidan 5 ta qatorni ekranga chiqaring!

In [ ]:
import requests
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/json_data.json"
r = requests.get(url)
df = pd.DataFrame(r.json())
df.head(5)

,Year,Total,Gas Fuel,Liquid Fuel,Solid Fuel,Cement,Gas Flaring,Per Capita
0,2010,9167,1702,3114,3842,450,59,1.33
1,2009,8740,1585,3056,3620,413,66,1.28
2,2008,8783,1631,3122,3571,388,71,1.30
3,2007,8566,1572,3081,3464,382,68,1.28
4,2006,8370,1525,3089,3339,356,61,1.27

#4-topshiriq
1. Quyida berilgan linkga `get` soʻrovini yuborish orqali `json` maʼlumotlarini `posts.json` fayliga saqlang.
  * https://jsonplaceholder.typicode.com/posts/
2. Ushbu maʼlumotlarni dataframe koʻrinishida saqlang va tasodifiy 5 ta qatorni ekranga chiqaring.

In [ ]:
url = "https://jsonplaceholder.typicode.com/posts/"
r = requests.get(url)

df1 = pd.DataFrame(r.json())
df1.to_json("posts.json")
df1.sample(5)

,userId,id,title,body
5,1,6,dolorem eum magni eos aperiam quia,ut aspernatur corporis harum nihil quis provid...
63,7,64,et fugit quas eum in in aperiam quod,id velit blanditiis\neum ea voluptatem\nmolest...
76,8,77,necessitatibus quasi exercitationem odio,modi ut in nulla repudiandae dolorum nostrum e...
62,7,63,voluptas blanditiis repellendus animi ducimus ...,enim adipisci aspernatur nemo\nnumquam omnis f...
47,5,48,ut voluptatem illum ea doloribus itaque eos,voluptates quo voluptatem facilis iure occaeca...