![Imgur](https://i.imgur.com/h4PPC71.png)
#**10-modul. Maʼlumotlarga ishlov berish. Fayllar va maʼlumotlar ombori**
#10.5. Fayldan oʻqish va unga yozish. HDF5
**Bu vazifalarni bajargach, CSV, Excel va HDF5 formatlarida fayllarni oʻqish hamda saqlash, yaʼni data processing (ma’lumotlarga ishlov berish) koʻnikmasini oʻzlashtirasiz.**


#1-topshiriq


1.    Quyidagi link orqali maʼlumotlarni Pandas dataframeʼiga yuklab oling.
    
  *   https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv



2.   Yuklab olingan maʼlumotlarni `aqi.csv` fayliga saqlang.

3. Saqlab olingan `aqi.csv` faylining oxirgi 5 ta qatorini oʻqing.

Eslatma: fayl nomini `aqi.csv` deb saqlaganimizning sababi AQI – Air Quality Index, yaʼni havo sifati indeksi deganidir. Bizning maʼlumotlarimizda davlatlarning havo sifati haqidagi maʼlumotlar saqlangan!

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/data_date.csv"
df = pd.read_csv(url)
df.to_csv("aqi.csv", index=False)
pd.read_csv("aqi.csv", nrows= 5)

         Date    Country                          Status  AQI Value
0  2022-07-21    Albania                            Good         14
1  2022-07-21    Algeria                        Moderate         65
2  2022-07-21    Andorra                        Moderate         55
3  2022-07-21     Angola  Unhealthy for Sensitive Groups        113
4  2022-07-21  Argentina                        Moderate         63

#2-topshiriq
1. Saqlab olingan `aqi.csv` faylidagi maʼlumotlarning faqat 2024-yilga tegishlisini excel faylga `aqi_2024.xlsx` koʻrinishida saqlab oling.
2. Saqlab olingan `aqi_2024.xlsx` faylidan Oʻzbekistonga tegishli maʼlumotni (qatorlarni) oʻqing.

In [ ]:
df2 = pd.read_csv("aqi.csv")
df_2024 = df2[df2['Date'].str.startswith('2024')]
df_2024.to_excel("aqi_2024.xlsx", index=False)

df3 = pd.read_excel("aqi_2024.xlsx",)
df_uzb = df3[df3['Country'].str.contains("Uzbekistan|O\'zbekiston")]
df_uzb

            Date     Country     Status  AQI Value
128   2024-06-06  Uzbekistan       Good         21
261   2024-06-06  Uzbekistan       Good         21
394   2024-06-13  Uzbekistan       Good         35
525   2024-06-20  Uzbekistan       Good         10
656   2024-06-27  Uzbekistan       Good         26
786   2024-07-04  Uzbekistan       Good         19
914   2024-07-11  Uzbekistan       Good         26
1043  2024-07-18  Uzbekistan       Good         42
1173  2024-07-25  Uzbekistan       Good         30
1302  2024-08-01  Uzbekistan       Good         45
1432  2024-08-08  Uzbekistan       Good         42
1562  2024-08-15  Uzbekistan       Good         26
1691  2024-08-22  Uzbekistan       Good         23
1819  2024-08-29  Uzbekistan   Moderate         56
1948  2024-09-05  Uzbekistan   Moderate         70
2075  2024-09-12  Uzbekistan       Good         45
2204  2024-09-19  Uzbekistan  Hazardous        500
2331  2024-09-26  Uzbekistan  Unhealthy        157
2450  2024-10-03  Uzbekistan       Good         34
2578  2024-10-10  Uzbekistan   Moderate         63
2700  2024-10-17  Uzbekistan  Unhealthy        195
2821  2024-10-24  Uzbekistan  Unhealthy        180
2941  2024-10-31  Uzbekistan  Unhealthy        153
3060  2024-11-07  Uzbekistan   Moderate         65
3179  2024-11-14  Uzbekistan  Unhealthy        151
3297  2024-11-21  Uzbekistan  Unhealthy        152
3419  2024-11-28  Uzbekistan       Good         38
3541  2024-12-05  Uzbekistan   Moderate         83
3663  2024-12-12  Uzbekistan   Moderate        100
3786  2024-12-19  Uzbekistan       Good         34
3907  2024-12-26  Uzbekistan   Moderate         98

#3-topshiriq
1. `aqi.csv` faylidagi maʼlumotlarni oʻrganib chiqsangiz, bu faylda 2022–2025-yillar oraligʻidagi havo sifati haqidagi maʼlumotlarni koʻrishingiz mumkin. Hozir sizga vazifa:
  * `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllariga `aqi.csv` faylidagi maʼlumotlarning mos davrlarini saqlang. Misol uchun, `aqi_2022` fayli 2022-yildagi havo sifati haqidagi maʼlumotlarni oʻzida saqlaydi.

In [ ]:
for year in range(2022,2026) :
  df4 = pd.read_csv("aqi.csv")
  df5 = df4[df4['Date'].str.startswith(f'{year}')]
  df5.to_csv(f"aqi_{year}.csv", index=False)

#4-topshiriq
1. Saqlab olingan `aqi_2022.csv`, `aqi_2023.csv`, `aqi_2024.csv`, `aqi_2025.csv`  fayllarini HDF5 formatida saqlang. Fayl nomini `aqi.h5` deb nomlang. Kalit (key) sifatida fayllarning yillarini bering. Misol uchun, key=2025.

In [ ]:
hdf_obj = pd.HDFStore("aqi.h5")
for year in range(2022,2026) :
  df_year = pd.read_csv(f"aqi_{year}.csv")
  hdf_obj[f'year_{year}'] = df_year
hdf_obj.close()

#5-topshiriq
1. `aqi.h5` faylidan maʼlumotlarni oʻqing va 2025-yilga tegishli maʼlumotlarni yangi dataframeʼga saqlang.
2. `aqi.h5` faylida 2025-yilning qaysi oylari uchun maʼlumotlar bor? Shu oylar roʻyxatini ekranga chiqaring!

In [ ]:
import pandas as pd
df_2025 = pd.read_hdf("aqi.h5", key='year_2025')
df_2025['Date'] = pd.to_datetime(df_2025['Date'])
months = df_2025['Date'].dt.month_name().unique()
print(list(months))

['January', 'February', 'March']